### ISSUE TITLE
Blocks became air during the corld conversion

### ISSUE THREAD

**Issue by BeastSoup666** [Conquest-Reforged/WorldConverter#5]
There are a few blocks that didnt transfer correctly during the World conversion.

Birch Beam Fence Gate became some random gate

Roman Brick with Peach Stucco became air

Empty small rack's are rotated in the wrong directions 

Some Bush types became Common full grown Beans

Dark Oak Beam Fence Gate became air

The Wall variants of certain Shingles and Roof tiles became air

Certain Anvil variants of blocks bacame fullblocks or air

Carved Wood variants became fullblocks

Animal blocks such as bluejay and crow become invisible but reappear after being updated

Floating saplings become air

**Comment by HIPPOKLEIDES** [comment]
> Some Bush types became Common full grown Beans
>The Wall variants of certain Shingles and Roof tiles became air

Need specifics. Can't fix if I don't know which bush types or walls

>Roman Brick with Peach Stucco became air
>Empty small rack's are rotated in the wrong directions
>Floating saplings become air

Can be fixed

>Birch Beam Fence Gate became some random gate
>Dark Oak Beam Fence Gate became air

These don't exist in 1.15. To put it mildly we didn't like how they looked.

>Certain Anvil variants of blocks bacame fullblocks or air

Not all blocks that had anvils still have anvils. If an anvil that exists in 1.15 didn't get converted right, that can be fixed. Anvils 
that don't exist anymore would need mappings to another appropriate texture submitted. 

>Carved Wood variants became fullblocks

A carved wood block that had too many variants no longer has full array of variants

>Animal blocks such as bluejay and crow become invisible but reappear after being updated

No plans to resolve this since it doesn't require much effort to update them, yet would require a fair amount of effort on my part.

**Comment by HIPPOKLEIDES** [comment]
Stale issue, fixed a few of these
