### ISSUE TITLE
not all chunks converted

### ISSUE THREAD

**Issue by petrus-legend** [Conquest-Reforged/WorldConverter#7]
![2021-06-29_18 55 52](https://user-images.githubusercontent.com/61907578/123952793-c6521a00-d9a6-11eb-960a-2e3962ab1870.png)
windows 10, intel i9, 64 gb

i used the 1.12.2--->1.15.2 world converter but as you can see in the picture not all chunks were converted correctly. the chunks that werent converted correctly became just a regular ocean biome. i tried this multiple times but every time the exact same chunks werent converted.

how can i fix this?

**Comment by petrus-legend** [comment]
is anyone gonna help

**Comment by HIPPOKLEIDES** [comment]
Often this is caused by something odd with the world (running a bunch of other mods, accumulating junk from servers, being old, etc). I have taken builds from rather old worlds that simply don't convert well and pasted them into completely fresh worlds, resulting in those builds being converted perfectly without issue. Ardacraft (been running for years while carefully taking care of their world save) has reportedly managed to convert their 40k x 25k map without chunks missing.

I asssume this map was made with worldpainter. I'd recommend generating a fresh version of the map if you can, while converting any important builds into schematics you can paste into that fresh version.
